spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pratice;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security.oauth2: DEBUG

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
